export enum StatType {
    AbilityPower = 0,
    Armor = 1,
    Attack = 2,
    AttackSpeed = 3,
    AttackWindupTime = 4,
    MagicResist = 5,
    MoveSpeed = 6,
    CritChance = 7,
    CritDamage = 8,
    CooldownReduction= 9,
    AbilityHaste = 10,
    MaxHealth = 11,
    CurrentHealth= 12,
    PercentMissingHealth = 13,
    Unknown14 = 14,
    LifeSteal = 15,
    OmniVamp = 17,
    PhysicalVamp = 18,
    MagicPenetrationFlat = 19,
    MagicPenetrationPercent = 20,
    BonusMagicPenetrationPercent = 21,
    MagicLethality = 22,
    ArmorPenetrationFlat = 23,
    ArmorPenetrationPercent = 24,
    BonusArmorPenetrationPercent = 25,
    PhysicalLethality = 26,
    Tenacity = 27,
    AttackRange = 28,
    HealthRegenRate = 29,
    ResourceRegenRate = 30,
    Unknown31 = 31,
    Unknown32 = 32,
    DodgeChance = 33
}

export enum StatFormulaType {
    Base = 0,
    Bonus = 1,
    Total = 2,
    Unknown3 = 3,
    Unknown4 = 4
}